name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t crobindev/auditorium-reservation-backend:latest .

      - name: Push Image
        run: |
          docker login -u crobindev -p ${{ secrets.DOCKER_PASSWORD }}
          docker push crobindev/auditorium-reservation-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          script: |
            cd auditorium-reservation-backend
            git pull
            docker pull crobindev/auditorium-reservation-backend:latest
            docker compose down
            docker compose up -d
            make migrate-up
            docker images -f "dangling=true" -f "reference=crobindev/auditorium-reservation-backend" -q | xargs -r docker rmi
