name: Build

on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t crobindev/auditorium-reservation-backend:latest .

      - name: Push Image
        run: |
          docker login -u crobindev -p ${{ secrets.DOCKER_PASSWORD }}
          docker push crobindev/auditorium-reservation-backend:latest
